// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Heading field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Full Name Label field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.full_name_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_name_label: prismic.KeyTextField;

  /**
   * Email Label field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.email_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_label: prismic.KeyTextField;

  /**
   * Phone Label field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.phone_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_label: prismic.KeyTextField;

  /**
   * Message Label field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.message_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message_label: prismic.KeyTextField;

  /**
   * Button Text field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type FaqDocumentDataSlicesSlice = never;

/**
 * Content for Faq documents
 */
interface FaqDocumentData {
  /**
   * Heading field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Title field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Question1 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question1: prismic.KeyTextField;

  /**
   * Answer1 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer1: prismic.KeyTextField;

  /**
   * Question2 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question2: prismic.KeyTextField;

  /**
   * Answer2 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer2: prismic.KeyTextField;

  /**
   * Question3 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question3: prismic.KeyTextField;

  /**
   * Answer3 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer3: prismic.KeyTextField;

  /**
   * Question4 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question4: prismic.KeyTextField;

  /**
   * Answer4 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer4: prismic.KeyTextField;

  /**
   * Question5 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question5: prismic.KeyTextField;

  /**
   * Answer5 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer5: prismic.KeyTextField;

  /**
   * Question6 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question6: prismic.KeyTextField;

  /**
   * Answer6 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer6: prismic.KeyTextField;

  /**
   * Question7 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question7
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question7: prismic.KeyTextField;

  /**
   * Answer7 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer7
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer7: prismic.KeyTextField;

  /**
   * Question8 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question8
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question8: prismic.KeyTextField;

  /**
   * Answer8 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer8
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer8: prismic.KeyTextField;

  /**
   * Question9 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question9
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question9: prismic.KeyTextField;

  /**
   * Answer9 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer9
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer9: prismic.KeyTextField;

  /**
   * Question10 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question10
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question10: prismic.KeyTextField;

  /**
   * Answer10 field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.answer10
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer10: prismic.KeyTextField;

  /**
   * Slice Zone field in *Faq*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice> /**
   * Meta Title field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Faq*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Faq document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Quick Links field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quick_links: prismic.KeyTextField;

  /**
   * Home field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.home
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home: prismic.KeyTextField;

  /**
   * Features field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.features
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  features: prismic.KeyTextField;

  /**
   * Pricing field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.pricing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pricing: prismic.KeyTextField;

  /**
   * FAQ field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.faq
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  faq: prismic.KeyTextField;

  /**
   * Contact Us field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_us: prismic.KeyTextField;

  /**
   * Reach Out To Us field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.reach_out_to_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reach_out_to_us: prismic.KeyTextField;

  /**
   * Email Icon field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  email_icon: prismic.ImageField<never>;

  /**
   * Email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone Icon field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  phone_icon: prismic.ImageField<never>;

  /**
   * Phone field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Follow Us field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.follow_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  follow_us: prismic.KeyTextField;

  /**
   * LinkedIn Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.linkedin_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkedin_text: prismic.KeyTextField;

  /**
   * Facebook Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook_text: prismic.KeyTextField;

  /**
   * Legal field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  legal: prismic.KeyTextField;

  /**
   * Privacy Policy field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.privacy_policy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  privacy_policy: prismic.KeyTextField;

  /**
   * Terms And Conditions field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.terms_and_conditions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  terms_and_conditions: prismic.KeyTextField;

  /**
   * Button Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Meta Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: footer.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: footer.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = never;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Header Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * Features field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.features
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  features: prismic.KeyTextField;

  /**
   * Pricing field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pricing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pricing: prismic.KeyTextField;

  /**
   * Home field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.home
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home: prismic.KeyTextField;

  /**
   * Faq field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.faq
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  faq: prismic.KeyTextField;

  /**
   * Contact field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact: prismic.KeyTextField;

  /**
   * Button Text field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice> /**
   * Meta Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: header.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: header.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HirethebestDocumentDataSlicesSlice = never;

/**
 * Content for Hirethebest documents
 */
interface HirethebestDocumentData {
  /**
   * Heading field in *Hirethebest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hirethebest.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Hirethebest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hirethebest.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Getstarted button field in *Hirethebest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hirethebest.getstarted_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  getstarted_button: prismic.KeyTextField;

  /**
   * Requestdemo button field in *Hirethebest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hirethebest.requestdemo_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  requestdemo_button: prismic.KeyTextField;

  /**
   * Hire image field in *Hirethebest*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hirethebest.hire_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hire_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Hirethebest*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hirethebest.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HirethebestDocumentDataSlicesSlice> /**
   * Meta Title field in *Hirethebest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hirethebest.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Hirethebest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hirethebest.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Hirethebest*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hirethebest.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Hirethebest document from Prismic
 *
 * - **API ID**: `hirethebest`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HirethebestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HirethebestDocumentData>,
    "hirethebest",
    Lang
  >;

type OurvaluepropositionDocumentDataSlicesSlice = never;

/**
 * Content for Ourvalueproposition documents
 */
interface OurvaluepropositionDocumentData {
  /**
   * Top Heading field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.top_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_heading: prismic.KeyTextField;

  /**
   * Top Content field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.top_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_content: prismic.KeyTextField;

  /**
   * Values field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.values
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  values: prismic.KeyTextField;

  /**
   * Hiring Process field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.hiring_process
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hiring_process: prismic.KeyTextField;

  /**
   * Candidate Matching field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.candidate_matching
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  candidate_matching: prismic.KeyTextField;

  /**
   * Hiring Cost field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.hiring_cost
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hiring_cost: prismic.KeyTextField;

  /**
   * Assistance field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.assistance
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  assistance: prismic.KeyTextField;

  /**
   * Faster Hiring Heading field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.faster_hiring_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  faster_hiring_heading: prismic.KeyTextField;

  /**
   * Faster Hiring Content field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.faster_hiring_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  faster_hiring_content: prismic.KeyTextField;

  /**
   * Faster Hiring Score field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.faster_hiring_score
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  faster_hiring_score: prismic.KeyTextField;

  /**
   * Upward Image field in *Ourvalueproposition*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.upward_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  upward_image: prismic.ImageField<never>;

  /**
   * Downward Image field in *Ourvalueproposition*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.downward_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  downward_image: prismic.ImageField<never>;

  /**
   * Smart Matching Heading field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.smart_matching_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smart_matching_heading: prismic.KeyTextField;

  /**
   * Smart Matching Content field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.smart_matching_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smart_matching_content: prismic.KeyTextField;

  /**
   * Smart Matching Score field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.smart_matching_score
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smart_matching_score: prismic.KeyTextField;

  /**
   * Cost Efficient Heading field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.cost_efficient_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cost_efficient_heading: prismic.KeyTextField;

  /**
   * Cost Efficient Content field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.cost_efficient_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cost_efficient_content: prismic.KeyTextField;

  /**
   * Cost Efficient Score field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.cost_efficient_score
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cost_efficient_score: prismic.KeyTextField;

  /**
   * AI Assistance Heading field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.ai_assistance_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_assistance_heading: prismic.KeyTextField;

  /**
   * AI Assistance Content field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.ai_assistance_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_assistance_content: prismic.KeyTextField;

  /**
   * AI Assistance Score field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.ai_assistance_score
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_assistance_score: prismic.KeyTextField;

  /**
   * Slice Zone field in *Ourvalueproposition*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OurvaluepropositionDocumentDataSlicesSlice> /**
   * Meta Title field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ourvalueproposition.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Ourvalueproposition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ourvalueproposition.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Ourvalueproposition*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ourvalueproposition.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Ourvalueproposition document from Prismic
 *
 * - **API ID**: `ourvalueproposition`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OurvaluepropositionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OurvaluepropositionDocumentData>,
    "ourvalueproposition",
    Lang
  >;

type RevolutionizingDocumentDataSlicesSlice = never;

/**
 * Content for Revolutionizing documents
 */
interface RevolutionizingDocumentData {
  /**
   * Features field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.features
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  features: prismic.KeyTextField;

  /**
   * Top Heading field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.top_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_heading: prismic.KeyTextField;

  /**
   * Top Content field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.top_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_content: prismic.KeyTextField;

  /**
   * AI Powered field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.ai_powered
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_powered: prismic.KeyTextField;

  /**
   * Intelligent Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.intelligent_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  intelligent_image: prismic.ImageField<never>;

  /**
   * Intelligent field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.intelligent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intelligent: prismic.KeyTextField;

  /**
   * Job Description Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.job_description_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  job_description_image: prismic.ImageField<never>;

  /**
   * Job Description field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.job_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_description: prismic.KeyTextField;

  /**
   * AI Driven Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.ai_driven_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ai_driven_image: prismic.ImageField<never>;

  /**
   * AI Driven field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.ai_driven
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_driven: prismic.KeyTextField;

  /**
   * AI Powered Shortlisting Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.ai_powered_shortlisting_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ai_powered_shortlisting_image: prismic.ImageField<never>;

  /**
   * AI Powered Shortlisting field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.ai_powered_shortlisting
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_powered_shortlisting: prismic.KeyTextField;

  /**
   * Smart Interview Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.smart_interview_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  smart_interview_image: prismic.ImageField<never>;

  /**
   * Smart Interview field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.smart_interview
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smart_interview: prismic.KeyTextField;

  /**
   * Video Analytics Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.video_analytics_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_analytics_image: prismic.ImageField<never>;

  /**
   * Video Analytics field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.video_analytics
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_analytics: prismic.KeyTextField;

  /**
   * Seamless Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.seamless_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  seamless_image: prismic.ImageField<never>;

  /**
   * Seamless field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.seamless
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seamless: prismic.KeyTextField;

  /**
   * AI Powered Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.ai_powered_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  ai_powered_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Revolutionizing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RevolutionizingDocumentDataSlicesSlice> /**
   * Meta Title field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: revolutionizing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Revolutionizing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: revolutionizing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Revolutionizing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revolutionizing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Revolutionizing document from Prismic
 *
 * - **API ID**: `revolutionizing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RevolutionizingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RevolutionizingDocumentData>,
    "revolutionizing",
    Lang
  >;

type SubscriptionDocumentDataSlicesSlice = never;

/**
 * Content for Subscription documents
 */
interface SubscriptionDocumentData {
  /**
   * Pricing field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.pricing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pricing: prismic.KeyTextField;

  /**
   * Top Heading field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.top_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_heading: prismic.KeyTextField;

  /**
   * Top Content field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.top_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_content: prismic.KeyTextField;

  /**
   * Billed Monthly field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.billed_monthly
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  billed_monthly: prismic.KeyTextField;

  /**
   * Save up to field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.save_up_to
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  save_up_to: prismic.KeyTextField;

  /**
   * Billed Yearly field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.billed_yearly
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  billed_yearly: prismic.KeyTextField;

  /**
   * Small teams field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.small_teams
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  small_teams: prismic.KeyTextField;

  /**
   * Starter field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.starter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  starter: prismic.KeyTextField;

  /**
   * Free field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.free
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  free: prismic.KeyTextField;

  /**
   * Limited AI Resume Parsing  field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.limited_ai_resume_parsing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  limited_ai_resume_parsing: prismic.KeyTextField;

  /**
   * Basic Candidate Scoring field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.basic_candidate_scoring
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  basic_candidate_scoring: prismic.KeyTextField;

  /**
   * AI Interview field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.ai_interview
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_interview: prismic.KeyTextField;

  /**
   * Standard Job Posting  field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.standard_job_posting
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  standard_job_posting: prismic.KeyTextField;

  /**
   * Try for Free field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.try_for_free
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  try_for_free: prismic.KeyTextField;

  /**
   * Growing businesses field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.growing_businesses
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  growing_businesses: prismic.KeyTextField;

  /**
   * Pro field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.pro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pro: prismic.KeyTextField;

  /**
   * Growing businesses Value field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.growing_businesses_value
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  growing_businesses_value: prismic.KeyTextField;

  /**
   * month field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.month
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  month: prismic.KeyTextField;

  /**
   * Unlimited AI Resume Parsing field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.unlimited_ai_resume_parsing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  unlimited_ai_resume_parsing: prismic.KeyTextField;

  /**
   * Advanced Candidate Scoring field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.advanced_candidate_scoring
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  advanced_candidate_scoring: prismic.KeyTextField;

  /**
   * AI Driven Interviews field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.ai_driven_interviews
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_driven_interviews: prismic.KeyTextField;

  /**
   * Smart Job Description Optimization field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.smart_job_description_optimization
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smart_job_description_optimization: prismic.KeyTextField;

  /**
   * Interview Scheduling Automation field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.interview_scheduling_automation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  interview_scheduling_automation: prismic.KeyTextField;

  /**
   * Basic Analytics Dashboard field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.basic_analytics_dashboard
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  basic_analytics_dashboard: prismic.KeyTextField;

  /**
   * Large enterprises field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.large_enterprises
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  large_enterprises: prismic.KeyTextField;

  /**
   * Enterprise field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.enterprise
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  enterprise: prismic.KeyTextField;

  /**
   * Custom field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.custom
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom: prismic.KeyTextField;

  /**
   * Everything in Pro Plan field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.everything_in_pro_plan
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  everything_in_pro_plan: prismic.KeyTextField;

  /**
   * Custom AI Model field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.custom_ai_model
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_ai_model: prismic.KeyTextField;

  /**
   * ATS Integration field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.ats_integration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ats_integration: prismic.KeyTextField;

  /**
   * AI Powered Candidate field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.ai_powered_candidate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ai_powered_candidate: prismic.KeyTextField;

  /**
   * Dedicated Account Manager field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.dedicated_account_manager
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dedicated_account_manager: prismic.KeyTextField;

  /**
   * Advanced Analytics field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.advanced_analytics
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  advanced_analytics: prismic.KeyTextField;

  /**
   * Contact Us field in *Subscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.contact_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_us: prismic.KeyTextField;

  /**
   * `slices` field in *Subscription*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: subscription.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubscriptionDocumentDataSlicesSlice>;
}

/**
 * Subscription document from Prismic
 *
 * - **API ID**: `subscription`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubscriptionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SubscriptionDocumentData>,
    "subscription",
    Lang
  >;

export type AllDocumentTypes =
  | ContactDocument
  | FaqDocument
  | FooterDocument
  | HeaderDocument
  | HirethebestDocument
  | OurvaluepropositionDocument
  | RevolutionizingDocument
  | SubscriptionDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HirethebestDocument,
      HirethebestDocumentData,
      HirethebestDocumentDataSlicesSlice,
      OurvaluepropositionDocument,
      OurvaluepropositionDocumentData,
      OurvaluepropositionDocumentDataSlicesSlice,
      RevolutionizingDocument,
      RevolutionizingDocumentData,
      RevolutionizingDocumentDataSlicesSlice,
      SubscriptionDocument,
      SubscriptionDocumentData,
      SubscriptionDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
